
name: Docs

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  CMAKE_VERSION: 3.19.5

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && brew install enchant
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install exhale
        && pip3 install sphinx-sitemap
        && pip3 install recommonmark
        && pip3 install sphinxcontrib-spelling
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run: cd /
        && cmake --build /build --config Release --target Sphinx -- -j 14
        # && make html
        # && cd _build/html
        && cd build/docs/sphinx 
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        # FOLDER: docs/_build/html # The folder the action should deploy.
        FOLDER: build/docs/sphinx # The folder the action should deploy.
