
name: testaction

on: 
  push:
    branches: [ gitaction ]
  pull_request:
    branches: [ gitaction ]
  
env:
  CMAKE_VERSION: 3.19.5

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.7z",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.7z",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
    steps:
    - name: Requirements
      run: git clone https://github.com/fmtlib/fmt.git
        && cd fmt
        && mkdir build
        && cd build
        && cmake -DFMT_TEST=OFF -DFMT_DOC=OFF -DCMAKE_VERBOSE_MAKEFILE=ON ..
        && make
        && make install
        && cd ..
        && curl -L -O https://github.com/nlohmann/json/releases/download/v3.9.1/json.hpp
        && mkdir /usr/local/include/nlohmann
        && mv json.hpp /usr/local/include/nlohmann
        && git clone https://github.com/pboettch/json-schema-validator.git
        && cd json-schema-validator
        && mkdir build
        && cd build
        && cmake -Dnlohmann_json_DIR=/usr/local/include ..
        && make
        && sudo make install
