
name: testaction

on: 
  push:
    branches: [ gitaction ]
  pull_request:
    branches: [ gitaction ]
  
env:
  CMAKE_VERSION: 3.19.5

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: git clone https://github.com/fmtlib/fmt.git
        && cd fmt
        && mkdir build
        && cd build
        && cmake -DFMT_TEST=OFF -DFMT_DOC=OFF ..
        && make
        && make install
        && cd ..
        && curl -L -O https://github.com/nlohmann/json/releases/download/v3.9.1/json.hpp
        && mv json.hpp /usr/local/include
        && git clone https://github.com/pboettch/json-schema-validator.git
        && cd json-schema-validator
        && mkdir build
        && cd build
        && cmake -Dnlohmann_json_DIR=/usr/local/include ..
        && make
        && make install
